apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    url: http://victoriametrics:8428
    isDefault: true
    editable: false

  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    url: http://victorialogs:9429
    editable: false

  - name: VictoriaTraces
    type: jaeger
    url: http://victoriatraces:9428/select/jaeger
    editable: false
