"""drop_channel_transaction_id_from_payment_attempts

Revision ID: 6eebad41f9ca
Revises: ab517a0aa0b3
Create Date: 2026-04-03 19:04:51.642449

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6eebad41f9ca"
down_revision: str | Sequence[str] | None = "ab517a0aa0b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_transactions",
        sa.Column("payment_attempt_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("channel_transaction_id", sa.String(length=255), nullable=False),
        sa.Column("raw_callback_data", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_attempt_id"],
            ["payment_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payment_transactions_channel"), "payment_transactions", ["channel"], unique=False)
    op.create_index(
        op.f("ix_payment_transactions_channel_transaction_id"),
        "payment_transactions",
        ["channel_transaction_id"],
        unique=True,
    )
    op.create_index(op.f("ix_payment_transactions_order_id"), "payment_transactions", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_payment_transactions_payment_attempt_id"),
        "payment_transactions",
        ["payment_attempt_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payment_transactions_status"), "payment_transactions", ["status"], unique=False)
    op.drop_column("payment_attempts", "channel_transaction_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment_attempts", sa.Column("channel_transaction_id", sa.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f("ix_payment_transactions_status"), table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_payment_attempt_id"), table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_order_id"), table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_channel_transaction_id"), table_name="payment_transactions")
    op.drop_index(op.f("ix_payment_transactions_channel"), table_name="payment_transactions")
    op.drop_table("payment_transactions")
    # ### end Alembic commands ###
